# MMCLI Configuration File
# This file contains default settings for the multimedia CLI tool

[downloads]
# Default output directory for downloads
output_dir = "downloads"

# Default video settings
[downloads.video]
format = "mp4"                    # Default video format
resolution = "highest"           # Default resolution: "highest", "720p", "480p", etc.

# Default audio settings  
[downloads.audio]
format = "m4a"                   # Default audio format

# Playlist download settings
[downloads.playlist]
max_workers = 3                  # Number of parallel downloads (1 = sequential)
create_subfolders = true         # Create subfolders by playlist title
batch_convert = true             # Use batch conversion for format changes

[conversion]
# Default output directory for conversions
output_dir = "converter"

# Conversion quality settings
[conversion.video]
preserve_quality = true          # Preserve original quality when converting
default_codec = "libx264"        # Default video codec

[conversion.audio]
preserve_quality = true          # Preserve original quality when converting  
default_codec = "aac"            # Default audio codec
bitrate = "128k"                 # Default audio bitrate

[general]
# General application settings
verbose = false                  # Enable verbose output
progress_bar = true              # Show progress bars during operations
auto_cleanup = true              # Clean up temporary files automatically
max_retries = 3                  # Number of retry attempts on failure

# File naming settings
[general.naming]
add_timestamp = true             # Add timestamp to avoid filename conflicts
sanitize_filenames = true        # Remove special characters from filenames
max_filename_length = 255        # Maximum filename length